// src/app/reset-password/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { ShieldCheck, KeyRound, Check, CheckCircle2, ArrowLeft, ArrowRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'
import { toast } from 'sonner'
import { createClient } from '@/lib/supabase/client'
import Link from 'next/link'

const schema = z
  .object({
    password: z.string().min(8, 'Must be at least 8 characters'),
    confirmPassword: z.string().min(8, 'Must be at least 8 characters'),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: 'Passwords do not match',
    path: ['confirmPassword'],
  })

type FormData = z.infer<typeof schema>

export default function ResetPasswordPage() {
  const [updated, setUpdated] = useState(false)
  const [loading, setLoading] = useState(false)
  const router = useRouter()
  const supabase = createClient()

  const form = useForm<FormData>({
    resolver: zodResolver(schema),
    defaultValues: {
      password: '',
      confirmPassword: '',
    },
  })

  const onSubmit = async (data: FormData) => {
    setLoading(true)

    const { error } = await supabase.auth.updateUser({
      password: data.password,
    })

    setLoading(false)

    if (error) {
      toast.error('Error', {
        description: error.message,
      })
    } else {
      setUpdated(true)
    }
  }

  return (
    <div className="flex min-h-[calc(100vh-4rem)] items-center justify-center p-4 mt-16">
      <div className="w-full max-w-md">
        <Card className="shadow-2xl relative overflow-hidden ring-1 ring-stone-200 dark:ring-stone-700 rounded-2xl bg-stone-50 dark:bg-stone-900">
          <CardContent className="p-8 sm:p-10">
            {updated ? (
              <div className="text-center py-6">
                <div className="w-16 h-16 bg-emerald-100 dark:bg-emerald-900/30 rounded-full flex items-center justify-center mx-auto mb-6">
                  <CheckCircle2 className="w-8 h-8 text-emerald-800 dark:text-emerald-400" />
                </div>
                <h3 className="text-xl font-bold text-stone-900 dark:text-stone-50 mb-2">
                  Password updated
                </h3>
                <p className="text-stone-600 dark:text-stone-400 text-sm mb-6">
                  Your password has been successfully reset. You can now sign in with your new password.
                </p>
                <Button
                  asChild
                  className="w-full bg-emerald-900 hover:bg-emerald-950 h-12 text-base"
                >
                  <Link href="/login">
                    Sign In
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              </div>
            ) : (
              <>
                <div className="text-center mb-8">
                  <div className="w-14 h-14 bg-emerald-100 dark:bg-emerald-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
                    <ShieldCheck className="w-7 h-7 text-emerald-800 dark:text-emerald-400" />
                  </div>
                  <h1 className="text-2xl font-bold text-stone-900 dark:text-stone-50">
                    Set new password
                  </h1>
                  <p className="text-stone-600 dark:text-stone-400 mt-1 text-sm">
                    Choose a strong password for your account.
                  </p>
                </div>

                <Form {...form}>
                  <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5">
                    <FormField
                      control={form.control}
                      name="password"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-[10px] font-bold tracking-[0.15em] text-stone-700 dark:text-stone-300 uppercase">
                            New Password
                          </FormLabel>
                          <FormControl>
                            <div className="relative">
                              <KeyRound className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-stone-400" />
                              <Input
                                {...field}
                                type="password"
                                placeholder="At least 8 characters"
                                className="pl-10 bg-white dark:bg-stone-800 border-stone-300 dark:border-stone-600 h-11"
                              />
                            </div>
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="confirmPassword"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-[10px] font-bold tracking-[0.15em] text-stone-700 dark:text-stone-300 uppercase">
                            Confirm Password
                          </FormLabel>
                          <FormControl>
                            <div className="relative">
                              <KeyRound className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-stone-400" />
                              <Input
                                {...field}
                                type="password"
                                placeholder="Repeat your password"
                                className="pl-10 bg-white dark:bg-stone-800 border-stone-300 dark:border-stone-600 h-11"
                              />
                            </div>
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <div className="pt-2">
                      <Button
                        type="submit"
                        className="w-full bg-emerald-900 hover:bg-emerald-950 h-12 text-base"
                        disabled={loading}
                      >
                        {loading ? 'Updating...' : 'Update Password'}
                        {!loading && <Check className="ml-2 h-4 w-4" />}
                      </Button>
                    </div>
                  </form>
                </Form>

                <div className="mt-8 pt-6 border-t border-stone-200 dark:border-stone-700 text-center">
                  <Link
                    href="/login"
                    className="inline-flex items-center gap-1 text-sm font-medium text-emerald-700 dark:text-emerald-400 hover:text-emerald-900 dark:hover:text-emerald-300"
                  >
                    <ArrowLeft className="w-4 h-4" />
                    Back to sign in
                  </Link>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        <p className="text-center text-stone-400 dark:text-stone-500 text-[10px] mt-6 font-bold uppercase tracking-[0.25em]">
          Built for academic excellence
        </p>
      </div>
    </div>
  )
}

// app/pages/reset-password.vue
<script setup lang="ts">
import { z } from 'zod'
import type { FormSubmitEvent } from '#ui/types'

const supabase = useSupabaseClient()
const toast = useToast()
const loading = ref(false)
const updated = ref(false)

const state = reactive({
  password: undefined as string | undefined,
  confirmPassword: undefined as string | undefined
})

const schema = z.object({
  password: z.string().min(8, 'Must be at least 8 characters'),
  confirmPassword: z.string().min(8, 'Must be at least 8 characters')
}).refine(data => data.password === data.confirmPassword, {
  message: 'Passwords do not match',
  path: ['confirmPassword']
})

type Schema = z.output<typeof schema>

async function onSubmit(event: FormSubmitEvent<Schema>) {
  loading.value = true
  const { error } = await supabase.auth.updateUser({
    password: event.data.password
  })
  loading.value = false

  if (error) {
    toast.add({ title: 'Error', description: error.message, color: 'error' })
  } else {
    updated.value = true
  }
}
</script>

<template>
  <div class="flex min-h-[calc(100vh-4rem)] items-center justify-center p-4">
    <div class="w-full max-w-md">
      <UCard
        class="shadow-2xl relative overflow-hidden"
        :ui="{
          root: 'ring-1 ring-stone-200 dark:ring-stone-700 rounded-2xl bg-stone-50 dark:bg-stone-900',
          body: 'p-8 sm:p-10'
        }"
      >
        <!-- Success State -->
        <div v-if="updated" class="text-center py-6">
          <div class="w-16 h-16 bg-emerald-100 dark:bg-emerald-900/30 rounded-full flex items-center justify-center mx-auto mb-6">
            <UIcon name="i-lucide-check-circle-2" class="w-8 h-8 text-emerald-800 dark:text-emerald-400" />
          </div>
          <h3 class="text-xl font-bold text-stone-900 dark:text-stone-50 mb-2">
            Password updated
          </h3>
          <p class="text-stone-600 dark:text-stone-400 text-sm mb-6">
            Your password has been successfully reset. You can now sign in with your new password.
          </p>
          <UButton
            to="/login"
            block
            size="xl"
            color="success"
            variant="solid"
            trailing-icon="i-lucide-arrow-right"
            class="bg-emerald-900 hover:bg-emerald-950 shadow-lg transition-all duration-200 rounded-lg h-12"
          >
            Sign In
          </UButton>
        </div>

        <!-- Form State -->
        <template v-else>
          <div class="text-center mb-8">
            <div class="w-14 h-14 bg-emerald-100 dark:bg-emerald-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
              <UIcon name="i-lucide-shield-check" class="w-7 h-7 text-emerald-800 dark:text-emerald-400" />
            </div>
            <h1 class="text-2xl font-bold text-stone-900 dark:text-stone-50">
              Set new password
            </h1>
            <p class="text-stone-600 dark:text-stone-400 mt-1 text-sm">
              Choose a strong password for your account.
            </p>
          </div>

          <UForm :schema="schema" :state="state" @submit="onSubmit">
            <div class="space-y-5">
              <UFormField
                name="password"
                label="NEW PASSWORD"
                required
                :ui="{
                  label: 'text-[10px] font-bold tracking-[0.15em] text-stone-700 dark:text-stone-300 mb-2 uppercase',
                  container: 'space-y-0'
                }"
              >
                <UInput
                  v-model="state.password"
                  type="password"
                  placeholder="At least 8 characters"
                  size="lg"
                  icon="i-lucide-key-round"
                  :ui="{
                    base: 'bg-white dark:bg-stone-800 border border-stone-300 dark:border-stone-600 focus:border-emerald-800 focus:ring-1 focus:ring-emerald-800 rounded-lg'
                  }"
                />
              </UFormField>

              <UFormField
                name="confirmPassword"
                label="CONFIRM PASSWORD"
                required
                :ui="{
                  label: 'text-[10px] font-bold tracking-[0.15em] text-stone-700 dark:text-stone-300 mb-2 uppercase',
                  container: 'space-y-0'
                }"
              >
                <UInput
                  v-model="state.confirmPassword"
                  type="password"
                  placeholder="Repeat your password"
                  size="lg"
                  icon="i-lucide-key-round"
                  :ui="{
                    base: 'bg-white dark:bg-stone-800 border border-stone-300 dark:border-stone-600 focus:border-emerald-800 focus:ring-1 focus:ring-emerald-800 rounded-lg'
                  }"
                />
              </UFormField>

              <div class="pt-2">
                <UButton
                  type="submit"
                  block
                  size="xl"
                  color="success"
                  variant="solid"
                  :loading="loading"
                  trailing-icon="i-lucide-check"
                  class="bg-emerald-900 hover:bg-emerald-950 shadow-lg transition-all duration-200 rounded-lg h-12"
                >
                  Update Password
                </UButton>
              </div>
            </div>
          </UForm>

          <div class="mt-8 pt-6 border-t border-stone-200 dark:border-stone-700 text-center">
            <NuxtLink
              to="/login"
              class="inline-flex items-center gap-1 text-sm font-medium text-emerald-700 dark:text-emerald-400 hover:text-emerald-900 dark:hover:text-emerald-300"
            >
              <UIcon name="i-lucide-arrow-left" class="w-4 h-4" />
              Back to sign in
            </NuxtLink>
          </div>
        </template>
      </UCard>

      <p class="text-center text-stone-400 dark:text-stone-500 text-[10px] mt-6 font-bold uppercase tracking-[0.25em]">
        Built for academic excellence
      </p>
    </div>
  </div>
</template>
