// pages/index.vue
<template>
    <div class="space-y-4">
        <NuxtImg src="/img/logo_clear.png" sizes="175px md:350px" class="mx-auto" />

        <Card class="w-4/5 md:w-[25vw] mx-auto my-6">
            <template #title>
                <h3 class="mt-3">Inspiration</h3>
            </template>
            <template #content>
                <p class="m-0">I kinda wanted to make a portfolio site. It'd be kinda boring if I
                    only put coding projects though so I'm prolly gonna add my personal
                    projects too. I put a lil smidgin of my soul in all my work but now
                    that I've kind of hit a developer groove, I might as well put it in
                    one place.
                </p>
            </template>
        </Card>

        <!-- SOTD Hero -->
        <div class="text-center space-y-10">
            <h3 class="text-2xl">Songs of the Day</h3>
            <h3>SOTDs here</h3>
        </div>

        <p class="my-10 text-center">To share your own, <a href="http://twotone.app" class="underline">download TwoTone
                today</a> 😌</p>

        <h3>Projects</h3>
    </div>
</template>

<!-- <style lang="scss">
#hero {}
</style> -->

// pages/index.tsx
import { Container, Paper, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import MusicHero from "../components/individual/MusicHero";
import ProjectHero from "../components/individual/ProjectHero";

/**
 * @function Home
 * @fileoverview Need I say more?
 * TODO - Realtime interaction on SOTD
 * TODO - PWA Oppourtunity: Add push notifications for sotd. Minimal and respectful, only for repeat visitors
 */
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home | Tunji Productions</title>
        <meta
          name="description"
          content="Feel free to peruse, home of everything Sam"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        component={Paper}
        sx={{
          width: { xs: "80vw", sm: "70vw", md: "65vw", lg: "61vw" },
          py: 3,
          my: 5,
        }}
      >
        <Typography
          variant="h3"
          textAlign="center"
          sx={{ userSelect: "none", mb: 2 }}
        >
          Inspo
        </Typography>
        <Typography
          variant="body1"
          textAlign="center"
          sx={{ userSelect: "none" }}
        >
          I kinda wanted to make a portfolio site. It'd be kinda boring if I
          only put coding projects though so I'm prolly gonna add my personal
          projects too. I put a lil smidgin of my soul in all my work but now
          that I've kind of hit a developer groove, I might as well put it in
          one place.
        </Typography>
      </Container>
      <ProjectHero />
      <Typography
        variant="h3"
        textAlign="center"
        sx={{ userSelect: "none", my: 7, py: 3 }}
      >
        Song of the Day
      </Typography>
      <MusicHero />
    </>
  );
};

export default Home;
